name: Release Pipeline

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build project
        run: |
          echo "Building project..."

      - name: Create Release assets
        run: |
          zip -r project-release.zip .

      - name: Upload Release assets
        uses: actions/upload-artifact@v2
        with:
          name: project-release
          path: project-release.zip

